# Generated by Django 3.2.20 on 2023-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='recipeCollections',
            field=models.JSONField(default=list),
        ),
    ]
