# Generated by Django 3.2.20 on 2023-09-04 12:53

from django.db import migrations

def set_default_recipe_collections(apps, schema_editor):
    UserProfile = apps.get_model('myapp', 'UserProfile')
    UserProfile.objects.filter(recipeCollections__isnull=True).update(recipeCollections=[])

class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_userprofile_recipecollections'),
    ]

    operations = [
    ]
